Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2023-12, with the labels that each got.

#76 Add installation instructions for more Linux distributions in the README
  README.md
Labels: documentation

#73 pkg: Add more POCO apps, Change removal status, and Update incorrect grammar
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#96 Updated dependencies
  Cargo.lock
Labels: dependencies

#108 docs(contributing): add `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation

#118 Feature/standardized font size and layout fixes
  src/gui/mod.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
  src/gui/widgets/navigation_menu.rs
Labels: enhancement, UI (iced)

#111 pkg(`com.google.android.hotspot2.osulogin`): add package
  resources/assets/uad_lists.json
Labels: package::addition

#140 pkg(`com.transsion.magazineservice.xos`): add package
  resources/assets/uad_lists.json
Labels: package::addition

#139 pkg(`com.huawei.systemmanager`): add note to description
  resources/assets/uad_lists.json
Labels: package::documentation
