Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2023-11, with the labels that each got.

#46 added packages and changes description for some
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#59 pkg(`com.qualcomm.qcrilmsgtunnel`): change removal and description
  resources/assets/uad_lists.json
Labels: package::breakage

#58 pkg(`com.google.android.googlequicksearchbox`): improve description
  resources/assets/uad_lists.json
Labels: package::documentation

#63 docs(changelog): add packages
  CHANGELOG.md
Labels: documentation
