Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2023-10, with the labels that each got.

#4 Infinix recommendations
  resources/assets/uad_lists.json
Labels: package::documentation

#11 Anonymous wp all remaining patches
  README.md
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition, package::bootloop, package::breakage

#14 Fixed typos in uad_lists.json
  resources/assets/uad_lists.json
Labels: package::documentation

#16 com.android.companiondevicemanager edited
  resources/assets/uad_lists.json
Labels: package::documentation

#15 pkg addition: Wiko packages
  README.md
  resources/assets/uad_lists.json
Labels: package::addition

#18 ADB get all packages fix
  CHANGELOG.md
  src/core/sync.rs
  src/core/uad_lists.rs
Labels: bug

#21 added android.autoinstalls.config.Xiaomi.model
  CHANGELOG.md
  resources/assets/uad_lists.json
Labels: package::addition

#23 Updated camera description
  CHANGELOG.md
  resources/assets/uad_lists.json
Labels: package::documentation

#25 Added Package and Update Package Description
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition
