Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2024-08, with the labels that each got.

#573 pkg(Onyx): add Boox apps
  resources/assets/uad_lists.json
Labels: package::addition

#575 pkg(com.preff.kb.xm): add package
  resources/assets/uad_lists.json
Labels: package::addition

#537 build(linting): add more lints
  .github/release.yml
  Cargo.toml
  src/core/sync.rs
  src/gui/mod.rs
  src/gui/views/settings.rs
  src/gui/widgets/modal.rs
Labels: testing

#586 pkg(com.customermobile.preload.vzw): update description with security finding
  resources/assets/uad_lists.json
Labels: package::documentation

#587 chore(cargo): append ".toml" to `config`
  .cargo/config.toml
Labels: testing

#588 pkg(com.lge.sui.widget): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#593 pkg(com.android.chrome): add note about passkeys to description
  resources/assets/uad_lists.json
Labels: package::documentation
