Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2024-11, with the labels that each got.

#684 pkg(com.google.android.apps.messaging): add notice for Unihertz users
  resources/assets/uad_lists.json
Labels: package::documentation

#654 build(ci): add new unit tests
  src/core/config.rs
  src/gui/style.rs
Labels: testing

#714 pkg(com.taboola.scoop): add wallpaper carousel package
  resources/assets/uad_lists.json
Labels: package::addition

#734 pkg(com.samsung.android.dynamiclock) Breaks LockStar customizations
  resources/assets/uad_lists.json
Labels: package::breakage

#736 pkg(com.huawei.lbs): update description for Huawei LBS and change removal recommendation
  resources/assets/uad_lists.json
Labels: package::breakage

#739 pkg(com.lge.provider.signboard): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#735 pkg(com.android.se): dep of ColorOS lock
  resources/assets/uad_lists.json
Labels: package::breakage

#744 docs(readme): link to discussion about needing developers
  README.md
Labels: documentation
