Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2024-02, with the labels that each got.

#186 docs(readme): add FAQ item
  README.md
Labels: documentation

#209 pkg(om.nothing.cardservice): change `removal` and improve description
  resources/assets/uad_lists.json
Labels: package::documentation

#207 pkg(cn.wps.xiaomi.abroad.lite): improve description
  resources/assets/uad_lists.json
Labels: package::documentation

#216 feat(docs): Changelog generation improvement
  .github/release.yml
Labels: documentation, enhancement

#219 fix: typo in build_artifacts.yml
  .github/workflows/build_artifacts.yml
Labels: bug

#226 fix(program): redundant prepended 'v'
  src/gui/views/about.rs
Labels: bug

#191 Google Chromecast APKs
  resources/assets/uad_lists.json
Labels: package::addition

#230 feat(ui): don't force users to update without showing 'Apps' tab
  src/gui/style.rs
  src/gui/widgets/navigation_menu.rs
Labels: enhancement, UI (iced)

#233 fix(ci): Remove renderer matrix completely
  .github/workflows/build_artifacts.yml
Labels: enhancement

#235 pkg(com.heytap.pictorial): change removal and description
  resources/assets/uad_lists.json
Labels: package::documentation

#234 pkg(samsung): add package and changed description/removal
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#192 update some samsung pkgs
  resources/assets/uad_lists.json
Labels: package::documentation

#236 fix: strip `v` version prefix when checking for updates
  src/core/update.rs
Labels: bug

#238 fix: allow the app to display logs when launced from the terminal on windows
  Cargo.toml
  src/main.rs
Labels: bug

#243 lint: apply clippy suggestions
  Cargo.lock
  src/main.rs
Labels: bug

#241 pkg(samsung): update descriptions of `com.samsung.android.smartface` and `com.samsung.android.svcagent`
  resources/assets/uad_lists.json
Labels: package::documentation

#208 pkg(com.android.soundrecorder): improve description
  resources/assets/uad_lists.json
Labels: package::documentation

#232 pkg(samsung): add two packages
  resources/assets/uad_lists.json
Labels: package::addition

#247 Change package descriptions and categories
  resources/assets/uad_lists.json
Labels: package::documentation

#259 feat(ui): prepend v in front of version in navigation menu
  src/gui/widgets/navigation_menu.rs
Labels: enhancement

#252 Motorola more apps and better descriptions.
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#261 fix: pass user flag when sdk version is 21 or above
  src/core/sync.rs
Labels: bug

#269 feat(update): switch to using GitHub's latest release API
  src/core/update.rs
Labels: enhancement

#229 chore(issue-templates): improve default title text
  .github/ISSUE_TEMPLATE/add-new-package-s-.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/update-apps-description-or-recommendation.md
Labels: documentation

#245 XIAOMI MIBOX 4 APKS
  resources/assets/uad_lists.json
Labels: package::addition

#257 Update uad_lists.json, Duraspeed info
  resources/assets/uad_lists.json
Labels: package::documentation

#275 feat(ci): changed release notes to use github's auto generated one.
  .github/workflows/release.yml
Labels: enhancement

#279 chore(issue-templates): add documentation template
  .github/ISSUE_TEMPLATE/documentation.md
Labels: documentation

#203 refactor(program): make UAD-NG list have key value pair for directly building hashmap
  resources/assets/uad_lists.json
  src/core/uad_lists.rs
  src/core/utils.rs
  src/gui/views/list.rs
Labels: refactor

#287 fix(ci): sha256sum errors and overwrites
  .github/workflows/build_artifacts.yml
Labels: bug

#290 pkg(huawei-apps): add package and change descriptions
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#292 pkg(com.huawei.multimedia.audioengine): change description
  resources/assets/uad_lists.json
Labels: package::documentation

#293 pkg(com.google.android.apps.messaging): change description
  resources/assets/uad_lists.json
Labels: package::documentation

#282 chore(issue-templates): use issue forms
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-feature-request.yml
  .github/ISSUE_TEMPLATE/3-add-new-packages.yml
  .github/ISSUE_TEMPLATE/4-debloat-issue-report.yml
  .github/ISSUE_TEMPLATE/5-update-apps-description-or-recommendation.yml
  .github/ISSUE_TEMPLATE/6-documentation.yml
  .github/ISSUE_TEMPLATE/add-new-package-s-.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/debloat-issue-report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/update-apps-description-or-recommendation.md
Labels: documentation

#305 chore(issue-templates): fix typo in label
  .github/ISSUE_TEMPLATE/6-documentation.yml
Labels: bug

#307 chore(issue-templates): fix typos in labels
  .github/ISSUE_TEMPLATE/3-add-new-packages.yml
  .github/ISSUE_TEMPLATE/5-update-apps-description-or-recommendation.yml
Labels: bug

#296 pkg(com.sec.android.app.launcher): improve description
  resources/assets/uad_lists.json
Labels: package::documentation
