Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2024-04, with the labels that each got.

#397 pkg(com.android.keyguard): add warning for Mi Pad
  resources/assets/uad_lists.json
Labels: package::documentation

#395 pkg: replace Nitter URLs
  resources/assets/uad_lists.json
Labels: package::documentation

#406 pkg(com.vzw.hss.myverizon): change description
  resources/assets/uad_lists.json
Labels: package::documentation

#405 pkg(com.android.phone): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#407 pkg(com.sec.knox.switcher): add package
  resources/assets/uad_lists.json
Labels: package::addition

#408 docs(readme): add Matrix link
  README.md
Labels: documentation

#412 docs(readme): add DeepSource badges
  README.md
Labels: documentation, enhancement

#414 feat(app): exclude windows terminal attach
  src/main.rs
Labels: enhancement

#413 fix(ci): upload artifacts correctly
  .github/workflows/release.yml
Labels: bug

#402 pkg(samsung): add Samsung packages and improve documentation of some others
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#409 feat: graphically display error when adb command fails
  src/core/sync.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
Labels: enhancement, UI

#425 pkg(com.realme.as.music): add package
  resources/assets/uad_lists.json
Labels: package::addition

#422 refactor: reduce cycolmatic complexity
  src/gui/views/list.rs
Labels: refactor

#426 pkg(com.facemoji.lite.transsion): add info about potential breakage on Infinix phones
  resources/assets/uad_lists.json
Labels: package::documentation

#427 added new transsion packages
  resources/assets/uad_lists.json
Labels: package::addition

#433 fix(codecov): move serial environment variable name into constant
  src/core/sync.rs
  src/core/utils.rs
  src/gui/mod.rs
  src/gui/views/list.rs
Labels: bug

#431 pkg(com.dti.tracfone): add description for popular carrier bloatware installer
  resources/assets/uad_lists.json
Labels: package::addition
