Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2024-12, with the labels that each got.

#730 build(ci): fix macOS linting failing
  src/gui/style.rs
Labels: testing

#755 chore(issue-template): add ADB version field for bug-report
  .github/ISSUE_TEMPLATE/1-bug-report.yml
Labels: debug

#754 docs(readme): improve disclaimer and link to Rust website
  README.md
Labels: documentation

#737 pkg(htc): add HTC Lockscreen and Weather themes
  resources/assets/uad_lists.json
Labels: package::addition

#728 pkg(com.android.wallpaperbackup): fix typo in description
  resources/assets/uad_lists.json
Labels: package::documentation
