Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2024-05, with the labels that each got.

#439 pkg(com.oplus.safecenter): improve description
  resources/assets/uad_lists.json
Labels: package::documentation

#435 feat(backup): re-add export selection to text file
  src/core/utils.rs
  src/gui/views/list.rs
Labels: enhancement

#446 feat(ci): run the ci script on uad_list.json changes
  .github/workflows/ci.yml
Labels: enhancement

#452 bug(ui): visual bugs in selection review
  src/gui/views/list.rs
Labels: bug

#466 fix(ci): incorrect filename being used for UAD list
  .github/workflows/ci.yml
Labels: bug

#469 pkg(com.ape.mtbf): add Archive link for Twitter
  resources/assets/uad_lists.json
Labels: package::documentation

#457 pkg: add packages, improve descriptions and removals
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition, package::breakage

#470 feat(theming): add icon to Windows executable
  Cargo.lock
  Cargo.toml
  build.rs
  resources/assets/icon.ico
  resources/assets/manifest.rc
Labels: enhancement

#471 pkg(samsung): remove duplicate packages
  resources/assets/uad_lists.json
Labels: package::documentation

#472 pkg(oneplus): add OnePlus package
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#473 pkg: add packages, fix descriptions from issues section and from discord
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#481 pkg(me.phh.treble.app): add package for GSI ROM
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#482 pkg(samsung): add com.samsung.android.dbsc
  resources/assets/uad_lists.json
Labels: package::addition

#484 pkg: improve description and change removal of com.qualcomm.timeservice and com.google.android.configupdater
  resources/assets/uad_lists.json
Labels: package::documentation
