Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2024-07, with the labels that each got.

#528 pkg(com.lge.ims): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#527 feat(backup): add ability to export uninstalled packages with their description
  Cargo.lock
  Cargo.toml
  src/core/config.rs
  src/core/save.rs
  src/core/sync.rs
  src/core/theme.rs
  src/core/utils.rs
  src/gui/mod.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
  src/gui/widgets/modal.rs
Labels: enhancement

#533 hotfix(settings): patch regression and refactor a bit
  src/core/save.rs
  src/core/utils.rs
  src/gui/mod.rs
  src/gui/views/settings.rs
Labels: bug

#535 pkg(miui): change descriptions and removals based on potential bootloop
  resources/assets/uad_lists.json
Labels: package::documentation

#531 feat(theme): follow system theme by default
  src/core/config.rs
  src/core/theme.rs
  src/core/utils.rs
Labels: enhancement

#561 pkg(com.google.android.googlequicksearchbox): improve description
  resources/assets/uad_lists.json
Labels: package::documentation

#567 fix(uad_lists): add missing quotes
  resources/assets/uad_lists.json
Labels: bug
