Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2024-06, with the labels that each got.

#492 pkg(samsung/qualcomm): update descriptions
  resources/assets/uad_lists.json
Labels: package::documentation

#496 pkg(com.samsung.samsungpssdplus): add Samsung Magician
  resources/assets/uad_lists.json
Labels: package::addition

#495 pkg(com.android.camera): fix typos in description
  resources/assets/uad_lists.json
Labels: package::documentation

#497 build(ci): fix ci not running for user-submitted PR
  .github/workflows/ci.yml
Labels: bug

#498 pkg(sony): add packages of Android TV
  resources/assets/uad_lists.json
Labels: package::addition

#424 pkg(samsung): add warning to descriptions
  resources/assets/uad_lists.json
Labels: package::documentation

#502 pkg(sony): raise removal level of Android TV packages
  resources/assets/uad_lists.json
Labels: package::documentation

#506 pkg(com.motorola.VirtualUiccPayment): update description
  resources/assets/uad_lists.json
Labels: package::documentation

#505 pkg(com.motorola.att.phone.extensions): update description
  resources/assets/uad_lists.json
Labels: package::documentation

#512 pkg(samsung): add com.samsung.android.adaptivebrightnessgo
  resources/assets/uad_lists.json
Labels: package::addition

#522 docs(com.oneplus.config): change description
  resources/assets/uad_lists.json
Labels: package::documentation

#504 pkg(miui.systemui.plugin): add note about breaking reboot menu
  resources/assets/uad_lists.json
Labels: package::documentation

#503 pkg(com.huawei.android.internal.app): add note about sharing function
  resources/assets/uad_lists.json
Labels: package::documentation

#524 pkg(sony): add packages
  resources/assets/uad_lists.json
Labels: package::addition
