Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2024-01, with the labels that each got.

#124 feat: rename project name to Universal Android Debloater Next Generation (UAD-ng)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/debloat-issue-report.md
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  LICENSE
  README.md
  resources/assets/uad_lists.json
  src/core/sync.rs
  src/core/update.rs
  src/core/utils.rs
  src/gui/mod.rs
  src/gui/views/about.rs
  src/gui/views/list.rs
  src/gui/widgets/navigation_menu.rs
Labels: documentation, help wanted

#131 docs(readme): add Discord invite
  README.md
Labels: enhancement

#154 docs: remove explicit mention of 'GUI'
  LICENSE
  README.md
Labels: documentation

#155 fix: grammar and repetitive descriptions
  resources/assets/uad_lists.json
Labels: package::documentation

#163 feat: add checksum making commands
  .github/workflows/build_artifacts.yml
Labels: enhancement

#167 pkg(`com.mi.android.globalminusscreen`): update description
  resources/assets/uad_lists.json
Labels: package::addition

#170 docs(readme): remove singular language
  README.md
Labels: documentation

#165 refactor: remove unused string inside enum variants
  src/gui/mod.rs
  src/gui/views/list.rs
  src/gui/widgets/navigation_menu.rs
Labels: refactor

#153 fix(workflow): release.yml workflow's build job runs when it shouldn't
  .github/workflows/release.yml
Labels: bug
