Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2024-09, with the labels that each got.

#597 docs(contributing): recommend `rebase` from `main`
  CONTRIBUTING.md
Labels: documentation

#581 pkg(oneplus): add packages and improve descriptions
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#600 pkg(samsung): add packages
  resources/assets/uad_lists.json
Labels: package::addition

#603 refactor(app_id): specify `iced::Settings.id`
  src/core/update.rs
  src/core/utils.rs
  src/gui/mod.rs
  src/gui/views/about.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
Labels: refactor

#609 pkg(infinix): inform about bootloop and change `removal` to `unsafe`
  resources/assets/uad_lists.json
Labels: package::documentation

#555 pkg(samsung): alt names, missing packs, `fmt` list
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#611 pkg(com.android.settingsaccessibility): add package
  resources/assets/uad_lists.json
Labels: package::addition

#606 chore(issue-template): improve correctness, privacy, and comprehensiveness
  .github/ISSUE_TEMPLATE/1-bug-report.yml
Labels: documentation

#621 docs(public-functions): add documentation for public functions in `sync.rs`
  src/core/sync.rs
Labels: documentation

#578 refactor(linting): fix warnings from #537
  Cargo.toml
  src/core/helpers.rs
  src/core/save.rs
  src/core/sync.rs
  src/core/theme.rs
  src/core/uad_lists.rs
  src/core/update.rs
  src/core/utils.rs
  src/gui/mod.rs
  src/gui/views/about.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
  src/gui/widgets/modal.rs
  src/main.rs
Labels: testing

#620 fix: use `pm block` and `pm clear` for sdk versions below 19
  src/core/sync.rs
Labels: bug

#610 pkg(motorola): add packages
  resources/assets/uad_lists.json
Labels: package::addition

#421 feat: add Nix flake
  flake.lock
  flake.nix
Labels: enhancement, help wanted, dependencies

#633 pkg(com.hoffnung): improve description
  resources/assets/uad_lists.json
Labels: package::documentation

#626 build(ci): optimize Cargo `release` for program
  Cargo.toml
Labels: testing

#637 pkg(com.google.android.setupwizard): improve description
  resources/assets/uad_lists.json
Labels: package::documentation

#648 pkg(com.miui.aod): add lock screen editor feature to description
  resources/assets/uad_lists.json
Labels: package::documentation

#634 pkg(com.miui.guardprovider): improve description
  resources/assets/uad_lists.json
Labels: package::documentation

#635 pkg(com.samsung.android.knox.app.networkfilter): change removal and description
  resources/assets/uad_lists.json
Labels: package::documentation

#636 pkg(samsung): change removal and descriptions of multiple packages
  resources/assets/uad_lists.json
Labels: package::documentation

#652 pkg(com.mig.play.games): add Funmax package
  resources/assets/uad_lists.json
Labels: package::addition

#655 refactor: Avoid `clone` in assignments
  src/core/config.rs
  src/gui/views/list.rs
Labels: refactor

#656 chore(`bug-report.yml`): collapse log contents
  .github/ISSUE_TEMPLATE/1-bug-report.yml
Labels: documentation
