Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2024-03, with the labels that each got.

#309 pkg: add Infinix packages
  resources/assets/uad_lists.json
Labels: package::addition

#314 docs(contributing): add new headers and guidelines
  CONTRIBUTING.md
Labels: documentation

#315 pkg(realme): add packages and fix typo
  resources/assets/uad_lists.json
Labels: package::addition

#321 feat(ui): consistent buttons placements and "update" wording
  src/gui/widgets/navigation_menu.rs
Labels: enhancement, UI

#325 pkg(huawei): update descriptions
  resources/assets/uad_lists.json
Labels: package::documentation

#327 chore(issue-template): fix incorrect placeholder
  .github/ISSUE_TEMPLATE/4-debloat-issue-report.yml
Labels: documentation

#322 pkg(huawei): add packages and change descriptions/removals
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#311 release(changelog): add and remove labels
  .github/release.yml
Labels: documentation

#333 pkg(vivo): add packages and change descriptions
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#335 pkg(com.oneplus.camera.service): add warning to description
  resources/assets/uad_lists.json
Labels: package::documentation

#312 pkg: update some samsung packages
  resources/assets/uad_lists.json
Labels: package::documentation

#334 bug(ui): toggle all checkbox and review button is not updated on selecting device
  src/gui/mod.rs
  src/gui/views/list.rs
Labels: bug, UI

#342 pkg: fix typos
  resources/assets/uad_lists.json
Labels: package::documentation

#341 pkg(com.hoffnung): warn user to disable instead of uninstall
  resources/assets/uad_lists.json
Labels: package::documentation

#351 pkg(com.sec.android.diagmonagent): add warning and change removal
  resources/assets/uad_lists.json
Labels: package::documentation

#331 deps(iced): upgrade iced to 0.12
  Cargo.lock
  Cargo.toml
  src/core/theme.rs
  src/gui/mod.rs
  src/gui/style.rs
  src/gui/views/about.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
  src/gui/widgets/modal.rs
  src/gui/widgets/navigation_menu.rs
  src/gui/widgets/package_row.rs
Labels: bug, dependencies

#337 docs(readme): specify user's expectations what UAD-ng users can and cannot do
  README.md
Labels: documentation

#344 fix(app): unused variable 'res' when building with no-self-update
  src/gui/mod.rs
Labels: bug

#348 fix(startup): refreshing doesn't make the "adb not installed" message disappear
  src/gui/mod.rs
Labels: bug

#340 feat(ui): "iconify" Settings button
  resources/assets/icons.ttf
  src/gui/mod.rs
  src/gui/widgets/navigation_menu.rs
Labels: enhancement, UI

#362 pkg(xiaomi): add packages
  resources/assets/uad_lists.json
Labels: package::addition

#365 docs(readme): clarify what the Wiki is used for
  README.md
Labels: documentation

#366 docs(contributing): improve release management
  CHANGELOG.md
  CONTRIBUTING.md
Labels: documentation

#367 pkg: add Xiaomi packages and improve documentation/removals of some other packages
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#369 refactor(app): use if-else instead of match over booleans
  src/gui/mod.rs
  src/gui/views/list.rs
Labels: refactor

#364 fix(theming): logo not visible on Windows 11 light mode
  Cargo.lock
  Cargo.toml
  resources/assets/logo-dark.png
  resources/assets/logo-light.png
  src/gui/mod.rs
Labels: bug

#371 bug(uad-list): json parsing error
  resources/assets/uad_lists.json
  src/core/update.rs
  src/gui/mod.rs
Labels: bug

#368 pkg: add many packages to list (before pending)
  resources/assets/uad_lists.json
Labels: package::documentation

#372 fix(update-check): when downloading an update failed, UAD-ng isn't verbose about it
  src/core/sync.rs
  src/gui/mod.rs
  src/gui/views/list.rs
  src/gui/widgets/navigation_menu.rs
Labels: bug

#373 fix(ui): toggle all checkboxes and review button is not updated on selected device
  src/gui/mod.rs
Labels: bug

#379 chore(release-preparation): update dependencies
  Cargo.lock
  Cargo.toml
Labels: dependencies

#391 pkg(com.heytap.headset): add package and change removal of `com.oplus.melody`
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#388 pkg(com.qti.qualcomm.datastatusnotification): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#387 pkg(com.qualcomm.qtil.btdsda): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#382 pkg(descriptions): replace Nitter URL by Archive.org URL
  resources/assets/uad_lists.json
Labels: package::documentation
