Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2024-10, with the labels that each got.

#664 docs(readme): fix broken invite and image
  README.md
  resources/images/icon_clyde_blurple_RGB.png
Labels: documentation

#671 pkg(com.samsung.android.game.gos): add notice about disabling
  resources/assets/uad_lists.json
Labels: package::documentation

#681 pkg(google): change description and removal for 2 packages
  resources/assets/uad_lists.json
Labels: package::documentation

#685 pkg(com.samsung.android.mobileservice): change removal to advanced
  resources/assets/uad_lists.json
Labels: package::documentation

#674 pkg(google): change overlay removals to expert
  resources/assets/uad_lists.json
Labels: package::documentation

#660 pkg(Alibaba): add AliExpress
  resources/assets/uad_lists.json
Labels: package::addition

#677 pkg(com.coloros.weather.service): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#675 pkg(com.casper.turkiye): add package
  resources/assets/uad_lists.json
Labels: package::addition

#676 pkg(com.nothing.thirdparty): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#673 pkg(com.coloros.recents): fix incorrect description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#672 pkg(com.google.android.apps.privacy.wildlife): add package
  resources/assets/uad_lists.json
Labels: package::addition

#682 pkg(com.samsung.euicc): change removal and improve description
  resources/assets/uad_lists.json
Labels: package::documentation

#680 pkg(tcl): add `com.jrdcom.urlreservedapp1`
  resources/assets/uad_lists.json
Labels: package::addition

#683 pkg(com.miui.aod): change removal to advanced
  resources/assets/uad_lists.json
Labels: package::documentation
