Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2025-07, with the labels that each got.

#1008 build: split `release` profile into `opt`
  Cargo.toml
Labels: ci

#1009 build(cargo): don't use `mold`
  .cargo/config.toml
  Cargo.toml
Labels: linux, ci

#1014 pkg(miui, aosp): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#949 build(deps): upgrade all dependencies but Iced
  Cargo.lock
  Cargo.toml
  src/core/adb.rs
  src/core/config.rs
  src/core/save.rs
  src/core/sync.rs
  src/core/uad_lists.rs
  src/core/update.rs
  src/core/utils.rs
  src/gui/mod.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
  src/gui/widgets/modal.rs
Labels: dependencies
