Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2025-03, with the labels that each got.

#864 build(rust-edition): migrate to Rust 2024
  Cargo.toml
  src/core/adb.rs
  src/core/config.rs
  src/core/save.rs
  src/core/sync.rs
  src/core/theme.rs
  src/core/uad_lists.rs
  src/core/update.rs
  src/core/utils.rs
  src/gui/mod.rs
  src/gui/style.rs
  src/gui/views/about.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
  src/gui/widgets/modal.rs
  src/gui/widgets/navigation_menu.rs
  src/gui/widgets/package_row.rs
  src/main.rs
Labels: dependencies, refactor

#879 hotfix(sync:users): revert UID parsing
  src/core/adb.rs
  src/core/sync.rs
Labels: documentation, refactor

#880 refactor(lint): fix/silence some lints
  Cargo.toml
  src/core/adb.rs
  src/core/config.rs
  src/core/save.rs
  src/core/sync.rs
  src/core/uad_lists.rs
  src/core/update.rs
  src/core/utils.rs
  src/gui/mod.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
  src/gui/widgets/navigation_menu.rs
Labels: documentation, refactor, ci

#885 log: `error`->`warn`, if no device found
  src/gui/views/list.rs
Labels: enhancement

#883 chore(issue-template): add CI issue template
  .github/ISSUE_TEMPLATE/7-ci.yml
  .github/release.yml
Labels: ci

#889 docs(release): add development process header
  CONTRIBUTING.md
  RELEASE.md
Labels: documentation

#895 hotfix(self-update): differentiate between Intel and Apple Silicon on MacOS and update Windows binary name
  src/core/update.rs
Labels: bug

#894 feat(GUI:view:about): show `adb version`
  src/core/adb.rs
  src/gui/views/about.rs
Labels: enhancement

#898 fix: fix all `cfg` shenanigans
  src/core/adb.rs
  src/gui/views/about.rs
Labels: bug

#868 pkg: improve GMS and WA desc
  resources/assets/uad_lists.json
Labels: package::documentation

#822 pkg(com.android.incallui): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#877 pkg(com.android.unisoc.telephony.server): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#743 pkg(samsung): add packages
  resources/assets/uad_lists.json
Labels: package::addition

#759 pkg(miui.systemui.plugin): improve description
  resources/assets/uad_lists.json
Labels: package::documentation
