Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2025-05, with the labels that each got.

#964 pkg(com.google.android.pixel.setupwizard): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#965 fix(sync): minor fixes
  src/core/sync.rs
Labels: bug

#966 pkg(com.oplus.trafficmonitor): update description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#940 refactor: `list_available_backup_user` and `CommandType`->`PackageInfo`
  src/core/adb.rs
  src/core/save.rs
  src/core/sync.rs
  src/core/update.rs
  src/core/utils.rs
  src/gui/mod.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
Labels: refactor
