Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2025-06, with the labels that each got.

#978 pkg(scope): Issues with SIM Manager, Package Removal, and Performance
  resources/assets/uad_lists.json
Labels: package::breakage

#979 pkg(com.oem.euiccpartnerapp): breaks sim manager Moto G 5G 2024
  resources/assets/uad_lists.json
Labels: package::documentation

#980 pkg(scope): com.samsung.android.providers.trash Samsung Voice Recorder Crash
  resources/assets/uad_lists.json
Labels: package::documentation

#983 pkg(scope): `com.sec.android.app.hwmoduletest` breaks after removing `com.samsung.android.providers.factory` on Samsung Galaxy phones
  resources/assets/uad_lists.json
Labels: package::documentation

#984 pkg(scope): com.google.android.safetycenter.resources
  resources/assets/uad_lists.json
Labels: package::documentation

#977 feat(search): allow searching in descriptions
  src/gui/views/list.rs
Labels: enhancement

#955 pkg(com.motorola.livewallpaper3.prebuilt.*): add Motorola Prebuilt themes
  resources/assets/uad_lists.json
Labels: package::addition

#990 pkg(media-storage): add info about indexing/caching
  resources/assets/uad_lists.json
Labels: package::documentation

#995 pkg(com.google.android.tungsten.setupwraith): change removal and description
  resources/assets/uad_lists.json
Labels: package::documentation

#1000 pkg(com.transsion.applock): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#1003 pkg(com.coloros.wifibackuprestore): change removal and description
  resources/assets/uad_lists.json
Labels: package::documentation
