Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2025-04, with the labels that each got.

#932 pkg(com.android.chrome): update description for clarity on functionality
  resources/assets/uad_lists.json
Labels: package::documentation

#943 pkg(cnn): remove duplicate
  resources/assets/uad_lists.json
Labels: package::documentation

#946 pkg(com.android.role.notes.enabled): add warning regarding Developer Options
  resources/assets/uad_lists.json
Labels: package::documentation

#945 pkg(com.android.global): update description and removal behaviour
  resources/assets/uad_lists.json
Labels: package::documentation

#944 pkg(oem): update descriptions and change removal status for dependencies related to Private space on Pixel devices
  resources/assets/uad_lists.json
Labels: package::breakage

#953 ci(cargo): improve linting
  .github/workflows/ci.yml
Labels: ci

#935 feat(log): single log-file (`const` name)
  src/main.rs
Labels: enhancement, debug
