Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2025-08, with the labels that each got.

#1033 feat(ui): add copy button to copy error messages
  src/gui/views/list.rs
Labels: enhancement

#1036 fix(list-description-crash): add null action on scroll
  src/gui/views/list.rs
Labels: bug, UI

#1044 build(script): use `embed_resource` appropriately
  build.rs
Labels: ci
