Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2025-02, with the labels that each got.

#812 pkg(distro): remove community distros
  resources/assets/uad_lists.json
Labels: package::addition

#817 pkg(com.android.intentresolver): improve description and change removal
  resources/assets/uad_lists.json
Labels: package::documentation

#797 pkg(com.miui.cloudservice and com.miui.micloudsync): update description
  resources/assets/uad_lists.json
Labels: package::documentation

#820 pkg: change descriptions and add packages
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#821 pkg(com.xiaomi.bluetooth): improve description
  resources/assets/uad_lists.json
Labels: package::documentation

#828 pkg(com.qualcomm.qti.uceshimservice): remove duplicate
  resources/assets/uad_lists.json
Labels: package::addition

#833 pkg(tcl): add packages
  resources/assets/uad_lists.json
Labels: package::addition

#832 pkg(com.oplus.pscanvas): add package
  resources/assets/uad_lists.json
Labels: package::addition

#834 pkg(com.qualcomm.qti.services.systemhelper): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#831 pkg(sony): improve description and change removal
  resources/assets/uad_lists.json
Labels: package::documentation

#829 pkg(com.mi.healthglobal): improve description
  resources/assets/uad_lists.json
Labels: package::documentation

#827 pkg(com.google.android.appsearch.apk): add package
  resources/assets/uad_lists.json
Labels: package::addition

#825 pkg(oplus/oppo/oneplus): add packages
  resources/assets/uad_lists.json
Labels: package::addition

#823 pkg(com.oplus.aiunit): change description and removal
  resources/assets/uad_lists.json
Labels: package::documentation

#824 pkg(com.google.android.photopicker): add package
  resources/assets/uad_lists.json
Labels: package::addition

#757 refactor(ADB): improve internal API
  Cargo.toml
  src/core/adb.rs
  src/core/config.rs
  src/core/mod.rs
  src/core/save.rs
  src/core/sync.rs
  src/core/utils.rs
  src/gui/mod.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
  src/gui/widgets/modal.rs
Labels: documentation, refactor

#808 refactor(deps): replace `static_init` by `LazyLock`
  Cargo.lock
  Cargo.toml
  src/core/adb.rs
  src/core/config.rs
  src/core/save.rs
  src/core/sync.rs
  src/core/theme.rs
  src/main.rs
Labels: refactor

#835 pkg(com.fintech.life): change description
  resources/assets/uad_lists.json
Labels: package::documentation

#850 fix: force `wgpu` to use dedicated/discrete graphics-card, to avoid Vulkan issues
  src/main.rs
Labels: bug

#852 fix: disable debug validation of pack-IDs
  src/core/adb.rs
Labels: bug

#854 build(ci): version-pin OS of runners
  .github/workflows/build_artifacts.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: ci

#858 fix: use advanced text shaping to prevent text being rendered as squares with certain fonts or CJK characters
  Cargo.toml
  clippy.toml
  src/core/uad_lists.rs
  src/gui/views/about.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
  src/gui/widgets/mod.rs
  src/gui/widgets/navigation_menu.rs
  src/gui/widgets/package_row.rs
  src/gui/widgets/text.rs
Labels: bug
