Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2025-01, with the labels that each got.

#780 pkg(com.xiaomi.market): categorize it as Advanced
  resources/assets/uad_lists.json
Labels: package::documentation

#768 pkg(com.samsung.android.aircommandmanager): "ACM" -> "FACM"
  resources/assets/uad_lists.json
Labels: package::documentation

#769 pkg(com.samsung.android.app.dtv.dmb): add package
  resources/assets/uad_lists.json
Labels: package::addition

#773 pkg(samsung): improve S-location related descriptions
  resources/assets/uad_lists.json
Labels: package::documentation

#777 pkg(samsung themes): add wallpaper breakage info, remove redundancy
  resources/assets/uad_lists.json
Labels: package::documentation

#778 pkg(samsung): fix grammar and formatting for some Galaxy packs
  resources/assets/uad_lists.json
Labels: package::documentation

#678 pkg(com.heytap.pictorial): add note about wallpaper carousel
  resources/assets/uad_lists.json
Labels: package::documentation

#783 pkg(com.android.thememanager): improve description
  resources/assets/uad_lists.json
Labels: package::documentation

#790 pkg(com.android.phone): improve description and change removal type
  resources/assets/uad_lists.json
Labels: package::documentation

#786 build(ci): remove DeepSource check
  .deepsource.toml
  .github/workflows/ci.yml
  README.md
Labels: testing

#788 chore(deps): upgrade to `dark-light` v2
  Cargo.lock
  Cargo.toml
  src/core/theme.rs
  src/gui/mod.rs
Labels: bug, dependencies, refactor

#791 build(ci): add runner for MacOS with Intel CPU
  .github/workflows/build_artifacts.yml
Labels: testing

#793 build(ci): remove exclude and add MacOS-13 to CI
  .github/workflows/build_artifacts.yml
Labels: testing

#796 bug(settings): use csv instead of txt for `uninstalled_packages`
  src/gui/views/settings.rs
Labels: bug

#799 refactor: extract UNINSTALLED_PACKAGES_FILE_NAME_FORMAT into a const
  src/core/utils.rs
  src/gui/views/settings.rs
Labels: refactor

#807 feat(ADB): retry `adb devices` only 3 times in debug builds
  src/core/sync.rs
Labels: debug

#806 feat(ui): clearer "All" filters
  src/core/uad_lists.rs
Labels: enhancement, UI

#805 pkg(google): improve description, add package
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition
