Repository Universal-Debloater-Alliance/universal-android-debloater-next-generation, pull requests merged in 2025-09, with the labels that each got.

#1074 pkg(Xiaomi): add App Finder
  resources/assets/uad_lists.json
Labels: package::addition

#1063 UPDATED: pkg(samsung, cyrus, google): add packages
  resources/assets/uad_lists.json
Labels: package::documentation, package::addition

#1097 move com.amazon.venezia to advanced
  resources/assets/uad_lists.json
Labels: package::documentation
